### ISSUE TITLE
Update for kernel 4.0.5

### ISSUE THREAD

**Issue by moaxcp** [rgwott/gentoo-vmware-modules-patch-kernel4.0.4#1]
Could you update this for kernel 4.0.5? or does it just work?

**Comment by rgwott** [comment]
Hi,
I am not a maintainer of the package or anything, therefore I haven't extensively tested the patch, but I don't think the API changes much between minor kernel revisions (like 4.0.4 to 4.0.5). Also, some days ago I received some feedback in a Gentoo Forums thread (https://forums.gentoo.org/viewtopic-p-7755570.html) saying that the patch worked for kernel 4.0.5, so it probably does. You are welcome to test it, and if it works, please don't forget to confirm your experience on the thread as well. =)
