### ISSUE TITLE
provide README.md

### ISSUE THREAD

**Issue by moaxcp** [rgwott/gentoo-vmware-modules-patch-kernel4.0.4#2]
Hello, I have had some issues getting these to work on my system. Could you provide some general instructions? I found this in the Gentoo forum but I've never used patches. Some general steps would be good to getting this working.

**Comment by rgwott** [comment]
Hi,
I will provide a README file shortly, thanks for pointing it out.
In the meantime, you are welcome to visit the following Gentoo Forums thread: https://forums.gentoo.org/viewtopic-p-7755570.html and follow the instructions there (in a few words, place the patch files in folder /etc/portage/patches/app-emulation/vmware-modules-279.3).
